### ISSUE TITLE
Launch day checklist

### ISSUE THREAD

**Issue by cjdd3b** [striblab/campfi-2018#12]
- [ ] Hide gov buttons
- [x] All data entered for House
- [ ] All data entered for Senate
- [ ] Data double-checked for House, Senate
- [ ] Headlines written
- [ ] Text blurbs written
- [ ] Headlines, text blurbs edited by Chase
- [ ] Condon check (if he wants)
- [ ] Clickability stuff in place (see #3)
- [ ] Link any other stories in?
- [ ] Fire when ready
